### ISSUE TITLE
please consider using a standard license

### ISSUE THREAD

**Issue by ulrichard** [gbishop/cython-hidapi#19]
I'm in the process of packaging your library for debian. Now there came up an issue with the license. It is short and simple, and the intention seems clear, but there might be some ambiguities. As debian is very strict with licenses, it would be helpful, if you could adopt one of the standard licenses. The Expat / MIT license would probably be the closest to what you currently have.
I'm actually packaging the following fork : https://github.com/trezor/cython-hidapi, and I'm going to ask the same question there as well. But since you are the original author, you would also have to agree to a license change.

**Comment by prusnak** [comment]
I think it makes sense to use the same license as hidapi (i.e. triple-license GPLv3 and BSD and HIDAPI license). I am for this change.

**Comment by gbishop** [comment]
Make it whatever you want. I'll accept a pull request that fixes it. I hate licenses and the noise that surrounds them.

**Comment by ulrichard** [comment]
Thanks a lot.
